services:
  jekyll:
    image: jekyll/jekyll:3.8
    container_name: union-website
    command: jekyll serve --config _config.yml,_config.dev.yml --watch --force_polling
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development

volumes:
  bundle_cache:
