services:
  jekyll:
    image: jekyll/jekyll:4.2.0
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    working_dir: /srv/jekyll
    command: >
      sh -c "gem install bundler:1.16.0 &&
             bundle _1.16.0_ install &&
             bundle _1.16.0_ exec jekyll serve --host 0.0.0.0 --port 4000"
